mongodb:
  image: mongo:2.6.11
  container_name: mongodb
  ports:
    - "27017:27017"
  volumes:
    - ../../resources:/resources
  expose:
    - "27017"
# command: bash -c " set -o monitor ; curl -o initData.js https://raw.githubusercontent.com/labcabrera/lemur/master/resources/initData.js; mongod --smallfiles & sleep 5; mongo localhost:27017/lemur initData.js; fg"
  command: bash -c " set -o monitor ; mongod --smallfiles & sleep 10; mongo localhost:27017/rmengine /resources/mongo-init-data.js; fg"
